# file: tasks/clustercheck.yml

- name: Stop all mysql daemons
  service:
    name: mysql
    state: stopped
  when: galera_conf['bootstrap']

- name: Bootstrap cluster
  shell: service mysql bootstrap-pxc
  when: galera_conf['bootstrap'] and groups['galera_cluster'].index(inventory_hostname) == 0

- name: Start Sync
  shell: service mysql start
  when: galera_conf['bootstrap'] and groups['galera_cluster'].index(inventory_hostname) != 0