---
# Create link if not already exists. Upstart for mysql needs this! 
- name: create mtab if not exists
  command: /bin/ls /proc/mounts /etc/mtab
  args:
    creates: /etc/mtab

- name: Install Percona XtraDB Cluster server (DEB)
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - percona-xtradb-cluster-server-5.6
    - python-mysqldb
    - xinetd
    - git
  when: ansible_os_family == 'Debian'

- name: Install Percona XtraDB Cluster server (YUM)
  yum: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - Percona-XtraDB-Cluster-56
    - MySQL-python
    - xinetd
    - git
  when: ansible_os_family == 'RedHat'