---
# file: tasks/main.yml

- debug: msg="hostvars={{hostvars}}"
- debug: msg="vars={{vars}}"
- debug: msg="groups={{groups}}"
#- include: misc.yml
- include: repo.yml
- include: install_galera.yml
- include: configure_galera.yml
- include: grants.yml
- include: clustercheck.yml
